# Generated by Django 5.2 on 2025-10-16 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, verbose_name='客户端ID')),
                ('modified_at', models.DateTimeField(verbose_name='修改时间')),
                ('uuid', models.CharField(max_length=255, unique=True, verbose_name='设备UUID')),
                ('timestamp', models.DateTimeField(verbose_name='记录时间')),
                ('ver', models.CharField(default='', max_length=255, null=True, verbose_name='版本号')),
            ],
            options={
                'db_table': 'heartbeat',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('uuid', models.CharField(max_length=255, verbose_name='设备UUID')),
                ('login_status', models.BooleanField(default=True, verbose_name='登录状态')),
            ],
            options={
                'verbose_name': '登录客户端',
                'verbose_name_plural': '登录客户端',
                'db_table': 'login_client',
                'ordering': ['-username'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('client_id', models.CharField(max_length=255, verbose_name='客户端ID')),
                ('uuid', models.CharField(max_length=255, verbose_name='设备UUID')),
                ('login_type', models.CharField(max_length=50, verbose_name='登录类型')),
                ('login_status', models.BooleanField(default=True, verbose_name='登录状态')),
                ('os', models.CharField(max_length=50, verbose_name='操作系统')),
                ('device_type', models.CharField(max_length=50, verbose_name='设备类型')),
                ('device_name', models.CharField(max_length=255, verbose_name='设备名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'login_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, verbose_name='客户端ID')),
                ('cpu', models.TextField(verbose_name='CPU信息')),
                ('device_name', models.CharField(max_length=255, verbose_name='主机名')),
                ('memory', models.CharField(max_length=50, verbose_name='内存')),
                ('os', models.TextField(verbose_name='操作系统')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('uuid', models.CharField(max_length=255, unique=True, verbose_name='设备UUID')),
                ('version', models.CharField(max_length=50, verbose_name='客户端版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '系统信息',
                'verbose_name_plural': '系统信息',
                'db_table': 'system_info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(verbose_name='标签描述')),
            ],
            options={
                'verbose_name': '标签',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('uuid', models.CharField(max_length=255, verbose_name='设备UUID')),
                ('token', models.CharField(max_length=255, verbose_name='令牌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='最后使用时间')),
            ],
            options={
                'verbose_name': '令牌',
                'verbose_name_plural': '令牌',
                'db_table': 'token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TagToClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.systeminfo', to_field='uuid', verbose_name='设备UUID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.tag', to_field='name', verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签与设备关系',
                'verbose_name_plural': '标签与设备关系',
                'db_table': 'tag_to_client',
            },
        ),
    ]
