# Generated by Django 5.2 on 2025-10-28 07:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, verbose_name='客户端ID')),
                ('modified_at', models.DateTimeField(verbose_name='修改时间')),
                ('uuid', models.CharField(max_length=255, unique=True, verbose_name='设备UUID')),
                ('timestamp', models.DateTimeField(verbose_name='记录时间')),
                ('ver', models.CharField(default='', max_length=255, null=True, verbose_name='版本号')),
            ],
            options={
                'db_table': 'heartbeat',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, verbose_name='客户端ID')),
                ('cpu', models.TextField(verbose_name='CPU信息')),
                ('device_name', models.CharField(max_length=255, verbose_name='主机名')),
                ('memory', models.CharField(max_length=50, verbose_name='内存')),
                ('os', models.TextField(verbose_name='操作系统')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('uuid', models.CharField(max_length=255, unique=True, verbose_name='设备UUID')),
                ('version', models.CharField(max_length=50, verbose_name='客户端版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '系统信息',
                'verbose_name_plural': '系统信息',
                'db_table': 'system_info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(max_length=50, verbose_name='标签颜色')),
                ('guid', models.CharField(max_length=50, verbose_name='GUID')),
            ],
            options={
                'verbose_name': '标签',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid',
                 models.CharField(default=uuid.UUID('6c77e616-b3ce-11f0-805e-a679e91f8861'), max_length=50, unique=True,
                                  verbose_name='GUID')),
                ('personal_name', models.CharField(max_length=50, verbose_name='地址簿名称')),
                ('personal_type', models.CharField(choices=[('public', '公开'), ('private', '私有')], default='public',
                                                   verbose_name='地址簿类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_create_user',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '个人地址簿',
                'verbose_name_plural': '个人地址簿',
                'db_table': 'personal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_personal',
                                            to='auth.group')),
                ('personal',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_group',
                                   to='db.personal')),
            ],
            options={
                'verbose_name': '用户组与个人地址簿关系',
                'verbose_name_plural': '用户组与个人地址簿关系',
                'db_table': 'group_personal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeerPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('personal',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_peer',
                                   to='db.personal', to_field='guid')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_personal',
                                           to='db.systeminfo')),
            ],
            options={
                'verbose_name': '用户组与个人地址簿关系',
                'verbose_name_plural': '用户组与个人地址簿关系',
                'db_table': 'peer_personal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, verbose_name='客户端ID')),
                ('login_status', models.BooleanField(default=True, verbose_name='登录状态')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                               to_field='username', verbose_name='用户名')),
                ('uuid',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.systeminfo', to_field='uuid',
                                   verbose_name='设备UUID')),
            ],
            options={
                'verbose_name': '登录客户端',
                'verbose_name_plural': '登录客户端',
                'db_table': 'login_client',
                'ordering': ['-username'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level',
                 models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误')], max_length=50,
                                  verbose_name='日志类型')),
                ('operation_type', models.CharField(
                    choices=[('add', '添加'), ('delete', '删除'), ('update', '更新'), ('query', '查询'),
                             ('other', '其他')], max_length=50, verbose_name='操作类型')),
                ('operation_object', models.CharField(
                    choices=[('tag', '标签'), ('client', '设备'), ('user', '用户'), ('token', '令牌'),
                             ('login_client', '登录客户端'), ('login_log', '登录日志'), ('log', '日志'),
                             ('tag_to_client', '标签与设备关系'), ('user_to_tag', '用户与标签关系'),
                             ('system_info', '系统信息'), ('heart_beat', '心跳包'), ('config', '配置'),
                             ('file', '文件'), ('file_to_client', '文件与设备关系'), ('file_to_tag', '文件与标签关系'),
                             ('file_to_user', '文件与用户关系'), ('file_to_file', '文件与文件关系')], max_length=50,
                    verbose_name='操作对象')),
                ('operation_result', models.CharField(choices=[('success', '成功'), ('fail', '失败')], max_length=50,
                                                      verbose_name='操作结果')),
                ('operation_detail', models.TextField(default='', null=True, verbose_name='操作详情')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('username', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to=settings.AUTH_USER_MODEL, to_field='username',
                                               verbose_name='用户名')),
                ('uuid',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.systeminfo', to_field='uuid',
                                   verbose_name='设备UUID')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
                'db_table': 'log',
                'ordering': ['-operation_time'],
            },
        ),
        migrations.CreateModel(
            name='AutidConnLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('conn_id', models.IntegerField(verbose_name='连接ID')),
                ('initiating_ip', models.CharField(max_length=50, verbose_name='发起IP')),
                ('session_id', models.CharField(max_length=50, null=True, verbose_name='会话ID')),
                ('type', models.IntegerField(verbose_name='类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('username', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to=settings.AUTH_USER_MODEL, to_field='username',
                                               verbose_name='用户名')),
                ('controlled_uuid',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditlog_controlled',
                                   to='db.systeminfo', to_field='uuid', verbose_name='被控端UUID')),
                ('controller_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='auditlog_controller', to='db.systeminfo',
                                                      to_field='uuid', verbose_name='控制端UUID')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditFileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conn_id', models.IntegerField(verbose_name='连接ID')),
                ('operation_type', models.IntegerField(default=1, verbose_name='操作类型')),
                ('operation_info', models.CharField(default='', null=True, verbose_name='操作信息')),
                ('is_file', models.BooleanField(verbose_name='是否文件')),
                ('remote_path', models.CharField(default='', null=True, verbose_name='远程路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('controlled_uuid', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='auditfile_controlled', to='db.systeminfo',
                                                      to_field='uuid', verbose_name='被控端UUID')),
                ('controller_uuid', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='auditfile_controller', to='db.systeminfo',
                                                      to_field='uuid', verbose_name='控制端UUID')),
            ],
            options={
                'verbose_name': '审计文件',
                'verbose_name_plural': '审计文件',
                'db_table': 'audit_file',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TagToClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_to_tag',
                                             to='db.systeminfo', to_field='uuid', verbose_name='设备UUID')),
                ('tag_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_to_peer', to='db.tag',
                                   verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签与设备关系',
                'verbose_name_plural': '标签与设备关系',
                'db_table': 'tag_to_client',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='令牌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='最后使用时间')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                               to_field='username', verbose_name='用户名')),
                ('uuid',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.systeminfo', to_field='uuid',
                                   verbose_name='设备UUID')),
            ],
            options={
                'verbose_name': '令牌',
                'verbose_name_plural': '令牌',
                'db_table': 'token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('personal',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_user',
                                   to='db.personal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_personal',
                                           to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': '用户与个人地址簿关系',
                'verbose_name_plural': '用户与个人地址簿关系',
                'db_table': 'user_personal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPrefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='userprofile_group', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile',
                                              to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户配置',
                'verbose_name_plural': '用户配置',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserToSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                               to_field='username', verbose_name='用户名')),
                ('uuid',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.systeminfo', to_field='uuid',
                                   verbose_name='设备UUID')),
            ],
            options={
                'verbose_name': '用户与设备关系',
                'verbose_name_plural': '用户与设备关系',
                'db_table': 'user_to_system',
            },
        ),
    ]
