# Generated by Django 5.2.8 on 2025-11-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='client_type',
            field=models.CharField(choices=[(1, 'web'), (2, 'client'), (3, 'api')], default='client', max_length=255,
                                   verbose_name='客户端类型'),
        ),
    ]
