# Generated by Django 5.2.8 on 2026-01-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerinfo',
            name='username',
            field=models.CharField(default='None', max_length=255, verbose_name='用户名'),
        ),
    ]
