version: '1.0'
name: pipeline-20251030
displayName: build-docker
triggers:
  trigger: auto
  push:
    tags:
      include:
        - v\d+\.\d+\.\d+
stages:
  - name: stage-7b412ea2
    displayName: 构建docker
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        commands:
          - echo $GITEE_TAG
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches: []
        notify: []
        strategy:
          retry: '0'
