version: '1.0'
name: pipeline-20251030
displayName: build-docker
triggers:
  trigger: auto
  push:
    tags:
      include:
        - v\d+\.\d+\.\d+
stages:
  - name: stage-7b412ea2
    displayName: 构建docker
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker_latest
        displayName: 镜像构建latest版本
        type: cert
        certificate: dcc590d0-9775-013e-14cd-46055990ae55
        tag: rustdesk_api:latest
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter:
          APP_VERSION: ${GITEE_BRANCH}
        notify:
          - certificate: 19b73520-9089-013d-19d6-3ee4d8100835
            events:
              - success
              - fail
              - cancel
              - skip
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: dingtalk
        strategy:
          retry: '0'
          resource: '{"limits":{"cpu":"4","memory":"8"}}'
      - step: build@docker
        name: build_docker
        displayName: 镜像构建指定版本
        type: cert
        certificate: dcc590d0-9775-013e-14cd-46055990ae55
        tag: rustdesk_api:${GITEE_BRANCH}
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter:
          APP_VERSION: ${GITEE_BRANCH}
        notify:
          - certificate: 19b73520-9089-013d-19d6-3ee4d8100835
            events:
              - success
              - fail
              - cancel
              - skip
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: dingtalk
        strategy:
          retry: '0'
          resource: '{"limits":{"cpu":"4","memory":"8"}}'
